export const rowData = [
  {
    name: 'John',
    department: 'HR',
    position: 'Manager',
    salary: 50000,
    age: 35,
    experience: 10,
    performance: 85.4,
    location: 'New York',
    projects: 4,
    status: 'Active',
  },
  {
    name: 'Sara',
    department: 'IT',
    position: 'Developer',
    salary: 60000,
    age: 29,
    experience: 5,
    performance: 91.2,
    location: 'London',
    projects: 6,
    status: 'Active',
  },
  {
    name: 'Mike',
    department: 'Finance',
    position: 'Analyst',
    salary: 55000,
    age: 32,
    experience: 7,
    performance: 88.7,
    location: 'Tokyo',
    projects: 3,
    status: 'On Leave',
  },
];

export default rowData;
