import { ColDef } from 'ag-grid-community'; // optional but helps with types

const tableData: ColDef[] = [
  {
    headerName: 'Name',
    field: 'name',
    width: 150,
    chartDataType: 'category',
    enableRowGroup: true,
  },
  {
    headerName: 'Department',
    field: 'department',
    width: 120,
    chartDataType: 'category',
    enableRowGroup: true,
    enablePivot: true,
    enableValue: false,
  },
  {
    headerName: 'Position',
    field: 'position',
    width: 180,
    chartDataType: 'category',
  },
  {
    headerName: 'Salary',
    field: 'salary',
    width: 120,
    chartDataType: 'series',
    type: 'numericColumn',
    enableValue: true,
    aggFunc: 'sum',
    valueFormatter: (params) => '$' + (params.value?.toLocaleString() || '0'),
  },
  {
    headerName: 'Age',
    field: 'age',
    width: 80,
    chartDataType: 'series',
    type: 'numericColumn',
    enableValue: true,
  },
  {
    headerName: 'Experience',
    field: 'experience',
    width: 100,
    chartDataType: 'series',
    type: 'numericColumn',
    enableValue: true,
    aggFunc: 'avg',
  },
  {
    headerName: 'Performance',
    field: 'performance',
    width: 110,
    chartDataType: 'series',
    type: 'numericColumn',
    enableValue: true,
    aggFunc: 'avg',
    cellRenderer: (params: any) => (params.value ? params.value.toFixed(1) : '0.0'),
  },
  {
    headerName: 'Location',
    field: 'location',
    width: 120,
    chartDataType: 'category',
    enableRowGroup: true,
    enablePivot: true,
  },
  {
    headerName: 'Projects',
    field: 'projects',
    width: 100,
    chartDataType: 'series',
    type: 'numericColumn',
    enableValue: true,
    aggFunc: 'sum',
  },
  {
    headerName: 'Status',
    field: 'status',
    width: 100,
    chartDataType: 'category',
  },
];

export default tableData;
