name: Update Contributors

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 UTC on the 1st day of every month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          use_username: true
          image_size: 50
          columns_per_row: 6
          commit_message: "docs: update contributors list"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
